### ISSUE TITLE
请问是否考虑将此仓库代码上传至 npm？

### ISSUE THREAD

**Issue by langyo** [Himself65/rrreol#1]
本人有想将其制作为 VSCode 插件的想法，所以希望能通过 npm 引用到此库

~~感觉搞竞赛用 VSCode 怪怪的？？~~
~~反正我是装个 GCC 直接在 VSCode 终端下 g++ 指令进行编译~~

**Comment by Himself65** [comment]
本项目目前仅处于设计阶段，不过我大概有了思路了，不过等我六月份放假了再说

将来会

- 丰富的测试方法，参考jest

- Cli功能以及UI操作

**Comment by Himself65** [comment]
目前的想法是node.js做底层支持，包括命令行和脚本
ui部分使用react

npm是肯定会传上去的

**Comment by Himself65** [comment]
#2
